export const sampleOutage = {
    someData: [
        
            {
                outageID: "819461",
                project: "USOF-7287",
                state: "Andhra Pradesh",
                siteID: "I-AP-CTPL-Tower-6004",
                villageName: "Village 1",
                censusCode: "585338",
                dateOfOccurance: "22-Dec-22",
                timeOfOccurance: "23:13:24",
                faultResolutionDate: "22-Dec-22",
                faultResolutionTime: "23:21:22",
                tisSecs: "478",
                tisMins: "7.97",
                category: "Power"
            },
            {
                outageID: "819448",
                project: "project 354",
                state: "Kashmir",
                siteID: "I-JK-BONY-Tower-6044",
                villageName: "Village 2",
                censusCode: "2596",
                dateOfOccurance: "22-Dec-22",
                timeOfOccurance: "21:44:15",
                faultResolutionDate: "22-Dec-22",
                faultResolutionTime: "21:51:15",
                tisSecs: "420",
                tisMins: "7",
                category: "Backhaul"
            },
            {
                outageID: "819454",
                project: "project 354",
                state: "Kashmir",
                siteID: "I-JK-NBRA-Tower-6040",
                villageName: "Village 3",
                censusCode: "917",
                dateOfOccurance: "22-Dec-22",
                timeOfOccurance: "20:38:15",
                faultResolutionDate: "22-Dec-22",
                faultResolutionTime: "20:50:24",
                tisSecs: "729",
                tisMins: "12.15",
                category: "Power"
            },
            {
                outageID: "836064",
                project: "project 354",
                state: "Kashmir",
                siteID: "I-JK-LEEH-Tower-6068",
                villageName: "Village 4",
                censusCode: "906",
                dateOfOccurance: "22-Dec-22",
                timeOfOccurance: "19:42:04",
                faultResolutionDate: "22-Dec-22",
                faultResolutionTime: "19:48:30",
                tisSecs: "386",
                tisMins: "6.43",
                category: "Backhaul"
            },
            {
                outageID: "836151",
                project: "LWE II",
                state: "Odisha",
                siteID: "I-OR-ABDA-Tower-6028",
                villageName: "Village 5",
                censusCode: "424599|424570|424596|424593|424569|424642|424595|424573|424597|424567|424565|424601|424598|424602|424594|424572|424604|424599|424603|424600",
                dateOfOccurance: "22-Dec-22",
                timeOfOccurance: "19:30:09",
                faultResolutionDate: "22-Dec-22",
                faultResolutionTime: "19:47:09",
                tisSecs: "1020",
                tisMins: "17",
                category: "Backhaul"
            },
            {
                outageID: "836087",
                project: "project 354",
                state: "Kashmir",
                siteID: "I-JK-LEEH-Tower-6068",
                villageName: "Village 4",
                censusCode: "906",
                dateOfOccurance: "22-Dec-22",
                timeOfOccurance: "19:01:30",
                faultResolutionDate: "22-Dec-22",
                faultResolutionTime: "19:38:03",
                tisSecs: "2193",
                tisMins: "36.55",
                category: "Backhaul"
            },
            {
                outageID: "840788",
                project: "LWE II",
                state: "Chhattisgarh",
                siteID: "I-MP-PAJR-Tower-6114",
                villageName: "Village 6",
                censusCode: "448321| 448317",
                dateOfOccurance: "22-Dec-22",
                timeOfOccurance: "18:22:00",
                faultResolutionDate: "22-Dec-22",
                faultResolutionTime: "19:10:00",
                tisSecs: "2914",
                tisMins: "48.57",
                category: "Backhaul"
            },
            {
                outageID: "840794",
                project: "LWE II",
                state: "Chhattisgarh",
                siteID: "I-MP-PAJR-Tower-6118",
                villageName: "Village 7",
                censusCode: "448382",
                dateOfOccurance: "22-Dec-22",
                timeOfOccurance: "18:22:00",
                faultResolutionDate: "22-Dec-22",
                faultResolutionTime: "19:10:00",
                tisSecs: "2914",
                tisMins: "48.57",
                category: "Backhaul"
            },
            {
                outageID: "840793",
                project: "LWE II",
                state: "Chhattisgarh",
                siteID: "I-MP-PAJR-Tower-6116",
                villageName: "Village 8",
                censusCode: "448406",
                dateOfOccurance: "22-Dec-22",
                timeOfOccurance: "18:22:00",
                faultResolutionDate: "22-Dec-22",
                faultResolutionTime: "19:10:00",
                tisSecs: "2913",
                tisMins: "48.55",
                category: "Backhaul"
            },
            {
                outageID: "840798",
                project: "LWE II",
                state: "Chhattisgarh",
                siteID: "I-MP-PAJR-Tower-6122",
                villageName: "Village 9",
                censusCode: "448372",
                dateOfOccurance: "22-Dec-22",
                timeOfOccurance: "18:22:00",
                faultResolutionDate: "22-Dec-22",
                faultResolutionTime: "19:10:00",
                tisSecs: "2914",
                tisMins: "48.57",
                category: "Backhaul"
            },
            {
                outageID: "840789",
                project: "LWE II",
                state: "Chhattisgarh",
                siteID: "I-MP-PAJR-Tower-6116",
                villageName: "Village 8",
                censusCode: "448397",
                dateOfOccurance: "22-Dec-22",
                timeOfOccurance: "18:22:00",
                faultResolutionDate: "22-Dec-22",
                faultResolutionTime: "19:10:00",
                tisSecs: "2914",
                tisMins: "48.57",
                category: "Backhaul"
            },
            {
                outageID: "836158",
                project: "LWE II",
                state: "Odisha",
                siteID: "I-OR-MOTU-Tower-6024",
                villageName: "Village 10",
                censusCode: "431155",
                dateOfOccurance: "22-Dec-22",
                timeOfOccurance: "17:48:15",
                faultResolutionDate: "22-Dec-22",
                faultResolutionTime: "18:02:33",
                tisSecs: "858",
                tisMins: "14.3",
                category: "Equipment"
            },
            {
                outageID: "836106",
                project: "project 354",
                state: "Jammu",
                siteID: "I-JK-ATOL-Tower-6026",
                villageName: "Village 11",
                censusCode: "4734",
                dateOfOccurance: "22-Dec-22",
                timeOfOccurance: "16:02:12",
                faultResolutionDate: "22-Dec-22",
                faultResolutionTime: "16:09:42",
                tisSecs: "450",
                tisMins: "7.5",
                category: "Backhaul"
            },
            {
                outageID: "840731",
                project: "LWE II",
                state: "Chhattisgarh",
                siteID: "I-MP-BHRH-Tower-6068",
                villageName: "Village 12",
                censusCode: "451348",
                dateOfOccurance: "22-Dec-22",
                timeOfOccurance: "15:55:00",
                faultResolutionDate: "22-Dec-22",
                faultResolutionTime: "17:05:00",
                tisSecs: "4203",
                tisMins: "70.05",
                category: "Backhaul"
            },
            {
                outageID: "836105",
                project: "project 354",
                state: "Jammu",
                siteID: "I-JK-ATOL-Tower-6026",
                villageName: "Village 11",
                censusCode: "4734",
                dateOfOccurance: "22-Dec-22",
                timeOfOccurance: "15:33:42",
                faultResolutionDate: "22-Dec-22",
                faultResolutionTime: "15:55:42",
                tisSecs: "1320",
                tisMins: "22",
                category: "Backhaul"
            },
            {
                outageID: "836104",
                project: "project 354",
                state: "Jammu",
                siteID: "I-JK-ATOL-Tower-6026",
                villageName: "Village 11",
                censusCode: "4734",
                dateOfOccurance: "22-Dec-22",
                timeOfOccurance: "14:39:42",
                faultResolutionDate: "22-Dec-22",
                faultResolutionTime: "15:31:42",
                tisSecs: "3120",
                tisMins: "52",
                category: "Backhaul"
            },
            {
                outageID: "836103",
                project: "project 354",
                state: "Jammu",
                siteID: "I-JK-ATOL-Tower-6026",
                villageName: "Village 11",
                censusCode: "4734",
                dateOfOccurance: "22-Dec-22",
                timeOfOccurance: "13:31:12",
                faultResolutionDate: "22-Dec-22",
                faultResolutionTime: "13:43:42",
                tisSecs: "750",
                tisMins: "12.5",
                category: "Backhaul"
            },
            {
                outageID: "836148",
                project: "502_MP",
                state: "Madhya Pradesh",
                siteID: "I-MP-PANS-Tower-6016",
                villageName: "Village 13",
                censusCode: "478464",
                dateOfOccurance: "22-Dec-22",
                timeOfOccurance: "13:20:04",
                faultResolutionDate: "22-Dec-22",
                faultResolutionTime: "14:11:51",
                tisSecs: "3107",
                tisMins: "51.78",
                category: "Backhaul"
            },
            {
                outageID: "836084",
                project: "project 354",
                state: "Kashmir",
                siteID: "I-JK-BONY-Tower-6044",
                villageName: "Village 2",
                censusCode: "2596",
                dateOfOccurance: "22-Dec-22",
                timeOfOccurance: "13:09:08",
                faultResolutionDate: "22-Dec-22",
                faultResolutionTime: "13:34:10",
                tisSecs: "1502",
                tisMins: "25.03",
                category: "Backhaul"
            },
            {
                outageID: "836143",
                project: "502_MP",
                state: "Madhya Pradesh",
                siteID: "I-MP-CHGI-Tower-6112",
                villageName: "Village 14",
                censusCode: "503627",
                dateOfOccurance: "22-Dec-22",
                timeOfOccurance: "12:42:12",
                faultResolutionDate: "22-Dec-22",
                faultResolutionTime: "12:49:42",
                tisSecs: "450",
                tisMins: "7.5",
                category: "Backhaul"
            },
            {
                outageID: "836146",
                project: "502_MP",
                state: "Madhya Pradesh",
                siteID: "I-MP-CHGI-Tower-6111",
                villageName: "Village 15",
                censusCode: "503626",
                dateOfOccurance: "22-Dec-22",
                timeOfOccurance: "12:42:12",
                faultResolutionDate: "22-Dec-22",
                faultResolutionTime: "12:49:12",
                tisSecs: "420",
                tisMins: "7",
                category: "Backhaul"
            },
            {
                outageID: "840768",
                project: "LWE II",
                state: "Chhattisgarh",
                siteID: "I-MP-LOAH-Tower-6012",
                villageName: "Village 16",
                censusCode: "449163 | 449164",
                dateOfOccurance: "22-Dec-22",
                timeOfOccurance: "12:04:00",
                faultResolutionDate: "22-Dec-22",
                faultResolutionTime: "13:25:00",
                tisSecs: "4834",
                tisMins: "80.57",
                category: "Backhaul"
            },
            {
                outageID: "836088",
                project: "project 354",
                state: "Kashmir",
                siteID: "I-JK-BONY-Tower-6044",
                villageName: "Village 2",
                censusCode: "2596",
                dateOfOccurance: "22-Dec-22",
                timeOfOccurance: "11:29:34",
                faultResolutionDate: "22-Dec-22",
                faultResolutionTime: "11:41:30",
                tisSecs: "716",
                tisMins: "11.93",
                category: "Backhaul"
            },
            {
                outageID: "836078",
                project: "project 354",
                state: "Kashmir",
                siteID: "I-JK-BONY-Tower-6044",
                villageName: "Village 2",
                censusCode: "2596",
                dateOfOccurance: "22-Dec-22",
                timeOfOccurance: "11:16:04",
                faultResolutionDate: "22-Dec-22",
                faultResolutionTime: "11:26:00",
                tisSecs: "596",
                tisMins: "9.93",
                category: "Backhaul"
            },
            {
                outageID: "836186",
                project: "Assam",
                state: "Assam",
                siteID: "I-AS-HFLG-Tower-6074",
                villageName: "Village 17",
                censusCode: "298406",
                dateOfOccurance: "22-Dec-22",
                timeOfOccurance: "11:07:23",
                faultResolutionDate: "22-Dec-22",
                faultResolutionTime: "12:07:22",
                tisSecs: "3600",
                tisMins: "60",
                category: "Power"
            },
            {
                outageID: "836148",
                project: "502_MP",
                state: "Madhya Pradesh",
                siteID: "I-MP-CHGI-Tower-6112",
                villageName: "Village 14",
                censusCode: "503627",
                dateOfOccurance: "22-Dec-22",
                timeOfOccurance: "10:16:42",
                faultResolutionDate: "22-Dec-22",
                faultResolutionTime: "12:13:42",
                tisSecs: "7020",
                tisMins: "117",
                category: "Backhaul"
            },
            {
                outageID: "836145",
                project: "502_MP",
                state: "Madhya Pradesh",
                siteID: "I-MP-CHGI-Tower-6111",
                villageName: "Village 15",
                censusCode: "503626",
                dateOfOccurance: "22-Dec-22",
                timeOfOccurance: "10:16:42",
                faultResolutionDate: "22-Dec-22",
                faultResolutionTime: "12:13:42",
                tisSecs: "7020",
                tisMins: "117",
                category: "Backhaul"
            },
            {
                outageID: "840737",
                project: "LWE II",
                state: "Chhattisgarh",
                siteID: "I-MP-BNDW-Tower-6066",
                villageName: "Village 18",
                censusCode: "447357",
                dateOfOccurance: "22-Dec-22",
                timeOfOccurance: "08:59:00",
                faultResolutionDate: "22-Dec-22",
                faultResolutionTime: "12:13:00",
                tisSecs: "11653",
                tisMins: "194.22",
                category: "Backhaul"
            },
            {
                outageID: "840784",
                project: "LWE II",
                state: "Chhattisgarh",
                siteID: "I-MP-NGRI-Tower-6106",
                villageName: "Village 19",
                censusCode: "447360",
                dateOfOccurance: "22-Dec-22",
                timeOfOccurance: "08:58:00",
                faultResolutionDate: "22-Dec-22",
                faultResolutionTime: "12:13:00",
                tisSecs: "11677",
                tisMins: "194.62",
                category: "Backhaul"
            },
            {
                outageID: "840787",
                project: "LWE II",
                state: "Chhattisgarh",
                siteID: "I-MP-NGRI-Tower-6114",
                villageName: "Village 20",
                censusCode: "447355",
                dateOfOccurance: "22-Dec-22",
                timeOfOccurance: "08:58:00",
                faultResolutionDate: "22-Dec-22",
                faultResolutionTime: "12:13:00",
                tisSecs: "11677",
                tisMins: "194.62",
                category: "Backhaul"
            },
            {
                outageID: "840786",
                project: "LWE II",
                state: "Chhattisgarh",
                siteID: "I-MP-NGRI-Tower-6111",
                villageName: "Village 21",
                censusCode: "447353",
                dateOfOccurance: "22-Dec-22",
                timeOfOccurance: "08:58:00",
                faultResolutionDate: "22-Dec-22",
                faultResolutionTime: "12:13:00",
                tisSecs: "11677",
                tisMins: "194.62",
                category: "Backhaul"
            },
            {
                outageID: "840785",
                project: "LWE II",
                state: "Chhattisgarh",
                siteID: "I-MP-NGRI-Tower-6110",
                villageName: "Village 22",
                censusCode: "447327",
                dateOfOccurance: "22-Dec-22",
                timeOfOccurance: "08:58:00",
                faultResolutionDate: "22-Dec-22",
                faultResolutionTime: "12:13:00",
                tisSecs: "11677",
                tisMins: "194.62",
                category: "Backhaul"
            },
            {
                outageID: "819478",
                project: "project 354",
                state: "Uttarakhand",
                siteID: "I-UW-MNAH-Tower-6006",
                villageName: "Village 23",
                censusCode: "53947",
                dateOfOccurance: "22-Dec-22",
                timeOfOccurance: "08:55:12",
                faultResolutionDate: "22-Dec-22",
                faultResolutionTime: "09:54:42",
                tisSecs: "3570",
                tisMins: "59.5",
                category: "Backhaul"
            },
            {
                outageID: "819480",
                project: "project 354",
                state: "Uttarakhand",
                siteID: "I-UW-MNAH-Tower-6007",
                villageName: "Village 24",
                censusCode: "53934",
                dateOfOccurance: "22-Dec-22",
                timeOfOccurance: "08:55:12",
                faultResolutionDate: "22-Dec-22",
                faultResolutionTime: "09:54:42",
                tisSecs: "3570",
                tisMins: "59.5",
                category: "Backhaul"
            },
            {
                outageID: "819488",
                project: "project 354",
                state: "Uttarakhand",
                siteID: "I-UW-MNAH-Tower-6008",
                villageName: "Village 25",
                censusCode: "53936",
                dateOfOccurance: "22-Dec-22",
                timeOfOccurance: "08:55:12",
                faultResolutionDate: "22-Dec-22",
                faultResolutionTime: "09:54:43",
                tisSecs: "3571",
                tisMins: "59.52",
                category: "Backhaul"
            },
            {
                outageID: "819494",
                project: "project 354",
                state: "Uttarakhand",
                siteID: "I-UW-PULL-Tower-6004",
                villageName: "Village 26",
                censusCode: "54380",
                dateOfOccurance: "22-Dec-22",
                timeOfOccurance: "08:55:12",
                faultResolutionDate: "22-Dec-22",
                faultResolutionTime: "09:54:43",
                tisSecs: "3571",
                tisMins: "59.52",
                category: "Backhaul"
            },
            {
                outageID: "840761",
                project: "LWE II",
                state: "Chhattisgarh",
                siteID: "I-MP-LOAH-Tower-6012",
                villageName: "Village 16",
                censusCode: "449163 | 449164",
                dateOfOccurance: "22-Dec-22",
                timeOfOccurance: "08:49:00",
                faultResolutionDate: "22-Dec-22",
                faultResolutionTime: "11:24:00",
                tisSecs: "9308",
                tisMins: "155.13",
                category: "Backhaul"
            },
            {
                outageID: "840786",
                project: "LWE II",
                state: "Chhattisgarh",
                siteID: "I-MP-BHRH-Tower-6068",
                villageName: "Village 12",
                censusCode: "451348",
                dateOfOccurance: "22-Dec-22",
                timeOfOccurance: "07:55:00",
                faultResolutionDate: "22-Dec-22",
                faultResolutionTime: "08:54:00",
                tisSecs: "3572",
                tisMins: "59.53",
                category: "Backhaul"
            },
            {
                outageID: "836068",
                project: "project 354",
                state: "Kashmir",
                siteID: "I-JK-KURA-Tower-6252",
                villageName: "Village 27",
                censusCode: "6",
                dateOfOccurance: "22-Dec-22",
                timeOfOccurance: "07:49:35",
                faultResolutionDate: "22-Dec-22",
                faultResolutionTime: "07:56:33",
                tisSecs: "418",
                tisMins: "6.97",
                category: "Backhaul"
            },
            {
                outageID: "836091",
                project: "project 354",
                state: "Kashmir",
                siteID: "I-JK-LEEH-Tower-6068",
                villageName: "Village 4",
                censusCode: "906",
                dateOfOccurance: "22-Dec-22",
                timeOfOccurance: "06:17:51",
                faultResolutionDate: "22-Dec-22",
                faultResolutionTime: "07:30:51",
                tisSecs: "4380",
                tisMins: "73",
                category: "Backhaul"
            },
            {
                outageID: "840734",
                project: "LWE II",
                state: "Chhattisgarh",
                siteID: "I-MP-BHRH-Tower-6071",
                villageName: "Village 28",
                censusCode: "451186",
                dateOfOccurance: "22-Dec-22",
                timeOfOccurance: "05:28:00",
                faultResolutionDate: "22-Dec-22",
                faultResolutionTime: "07:08:00",
                tisSecs: "5945",
                tisMins: "99.08",
                category: "Backhaul"
            },
            {
                outageID: "840784",
                project: "LWE II",
                state: "Chhattisgarh",
                siteID: "I-MP-BHRH-Tower-6068",
                villageName: "Village 12",
                censusCode: "451348",
                dateOfOccurance: "22-Dec-22",
                timeOfOccurance: "05:16:00",
                faultResolutionDate: "22-Dec-22",
                faultResolutionTime: "05:28:00",
                tisSecs: "720",
                tisMins: "12",
                category: "Backhaul"
            },
            {
                outageID: "836185",
                project: "Assam",
                state: "Assam",
                siteID: "I-AS-HMRN-Tower-6284",
                villageName: "Village 29",
                censusCode: "295382",
                dateOfOccurance: "22-Dec-22",
                timeOfOccurance: "04:03:12",
                faultResolutionDate: "22-Dec-22",
                faultResolutionTime: "04:16:42",
                tisSecs: "840",
                tisMins: "14",
                category: "Backhaul"
            },
            {
                outageID: "840791",
                project: "LWE II",
                state: "Chhattisgarh",
                siteID: "I-MP-PAJR-Tower-6122",
                villageName: "Village 9",
                censusCode: "448372",
                dateOfOccurance: "22-Dec-22",
                timeOfOccurance: "04:03:00",
                faultResolutionDate: "22-Dec-22",
                faultResolutionTime: "04:21:00",
                tisSecs: "1110",
                tisMins: "18.5",
                category: "Equipment"
            },
            {
                outageID: "836181",
                project: "Assam",
                state: "Assam",
                siteID: "I-AS-HMRN-Tower-6141",
                villageName: "Village 30",
                censusCode: "295694",
                dateOfOccurance: "22-Dec-22",
                timeOfOccurance: "03:52:12",
                faultResolutionDate: "22-Dec-22",
                faultResolutionTime: "04:10:42",
                tisSecs: "1140",
                tisMins: "19",
                category: "Backhaul"
            },
            {
                outageID: "836183",
                project: "Assam",
                state: "Assam",
                siteID: "I-AS-HMRN-Tower-6201",
                villageName: "Village 31",
                censusCode: "295686",
                dateOfOccurance: "22-Dec-22",
                timeOfOccurance: "03:52:12",
                faultResolutionDate: "22-Dec-22",
                faultResolutionTime: "04:10:42",
                tisSecs: "1140",
                tisMins: "19",
                category: "Backhaul"
            },
            {
                outageID: "836184",
                project: "Assam",
                state: "Assam",
                siteID: "I-AS-HMRN-Tower-6284",
                villageName: "Village 29",
                censusCode: "295382",
                dateOfOccurance: "22-Dec-22",
                timeOfOccurance: "03:27:42",
                faultResolutionDate: "22-Dec-22",
                faultResolutionTime: "03:55:12",
                tisSecs: "1620",
                tisMins: "27",
                category: "Backhaul"
            },
            {
                outageID: "840790",
                project: "LWE II",
                state: "Chhattisgarh",
                siteID: "I-MP-PAJR-Tower-6122",
                villageName: "Village 9",
                censusCode: "448372",
                dateOfOccurance: "22-Dec-22",
                timeOfOccurance: "03:27:00",
                faultResolutionDate: "22-Dec-22",
                faultResolutionTime: "03:59:00",
                tisSecs: "1921",
                tisMins: "32.02",
                category: "Equipment"
            },
            {
                outageID: "836180",
                project: "Assam",
                state: "Assam",
                siteID: "I-AS-HMRN-Tower-6141",
                villageName: "Village 30",
                censusCode: "295694",
                dateOfOccurance: "22-Dec-22",
                timeOfOccurance: "03:13:12",
                faultResolutionDate: "22-Dec-22",
                faultResolutionTime: "03:48:42",
                tisSecs: "2160",
                tisMins: "36",
                category: "Backhaul"
            },
            {
                outageID: "836188",
                project: "Assam",
                state: "Assam",
                siteID: "I-AS-HMRN-Tower-6201",
                villageName: "Village 31",
                censusCode: "295686",
                dateOfOccurance: "22-Dec-22",
                timeOfOccurance: "03:13:12",
                faultResolutionDate: "22-Dec-22",
                faultResolutionTime: "03:48:42",
                tisSecs: "2160",
                tisMins: "36",
                category: "Backhaul"
            },
            {
                outageID: "836164",
                project: "project 354",
                state: "Gujarat",
                siteID: "I-GJ-NSWD-Tower-6015",
                villageName: "Village 32",
                censusCode: "520723",
                dateOfOccurance: "22-Dec-22",
                timeOfOccurance: "02:36:17",
                faultResolutionDate: "22-Dec-22",
                faultResolutionTime: "02:54:48",
                tisSecs: "1111",
                tisMins: "18.52",
                category: "Backhaul"
            },
            {
                outageID: "836165",
                project: "project 354",
                state: "Gujarat",
                siteID: "I-GJ-NSWD-Tower-6017",
                villageName: "Village 33",
                censusCode: "520719",
                dateOfOccurance: "22-Dec-22",
                timeOfOccurance: "02:36:17",
                faultResolutionDate: "22-Dec-22",
                faultResolutionTime: "02:49:48",
                tisSecs: "811",
                tisMins: "13.52",
                category: "Backhaul"
            },
            {
                outageID: "836170",
                project: "project 354",
                state: "Himachal Pradesh",
                siteID: "I-HP-SPAK-Tower-6058",
                villageName: "Village 34",
                censusCode: "",
                dateOfOccurance: "22-Dec-22",
                timeOfOccurance: "02:10:00",
                faultResolutionDate: "22-Dec-22",
                faultResolutionTime: "14:21:00",
                tisSecs: "43860",
                tisMins: "731",
                category: "Power"
            },
            {
                outageID: "840783",
                project: "LWE II",
                state: "Chhattisgarh",
                siteID: "I-MP-BHRH-Tower-6068",
                villageName: "Village 12",
                censusCode: "451348",
                dateOfOccurance: "22-Dec-22",
                timeOfOccurance: "02:06:00",
                faultResolutionDate: "22-Dec-22",
                faultResolutionTime: "02:19:00",
                tisSecs: "781",
                tisMins: "13.02",
                category: "Backhaul"
            },
            {
                outageID: "840808",
                project: "USOF-7287",
                state: "Chhattisgarh",
                siteID: "I-MP-JGDP-Tower-6067",
                villageName: "Village 35",
                censusCode: "449153",
                dateOfOccurance: "22-Dec-22",
                timeOfOccurance: "01:35:00",
                faultResolutionDate: "22-Dec-22",
                faultResolutionTime: "01:41:00",
                tisSecs: "376",
                tisMins: "6.27",
                category: "Equipment"
            },
            {
                outageID: "836168",
                project: "project 354",
                state: "Gujarat",
                siteID: "I-GJ-NSWD-Tower-6015",
                villageName: "Village 32",
                censusCode: "520723",
                dateOfOccurance: "22-Dec-22",
                timeOfOccurance: "01:23:16",
                faultResolutionDate: "22-Dec-22",
                faultResolutionTime: "01:41:16",
                tisSecs: "1080",
                tisMins: "18",
                category: "Backhaul"
            },
            {
                outageID: "836163",
                project: "project 354",
                state: "Gujarat",
                siteID: "I-GJ-NSWD-Tower-6017",
                villageName: "Village 33",
                censusCode: "520719",
                dateOfOccurance: "22-Dec-22",
                timeOfOccurance: "01:23:16",
                faultResolutionDate: "22-Dec-22",
                faultResolutionTime: "01:41:16",
                tisSecs: "1080",
                tisMins: "18",
                category: "Backhaul"
            },
            {
                outageID: "836181",
                project: "AN",
                state: "West Bengal",
                siteID: "I-WB-FRGJ-Tower-6041",
                villageName: "Village 36",
                censusCode: "645472",
                dateOfOccurance: "22-Dec-22",
                timeOfOccurance: "01:22:24",
                faultResolutionDate: "22-Dec-22",
                faultResolutionTime: "01:32:29",
                tisSecs: "605",
                tisMins: "10.08",
                category: "Equipment"
            },
            {
                outageID: "836160",
                project: "project 354",
                state: "Gujarat",
                siteID: "I-GJ-NSWD-Tower-6015",
                villageName: "Village 32",
                censusCode: "520723",
                dateOfOccurance: "22-Dec-22",
                timeOfOccurance: "00:47:45",
                faultResolutionDate: "22-Dec-22",
                faultResolutionTime: "01:20:16",
                tisSecs: "1951",
                tisMins: "32.52",
                category: "Backhaul"
            },
            {
                outageID: "836161",
                project: "project 354",
                state: "Gujarat",
                siteID: "I-GJ-NSWD-Tower-6017",
                villageName: "Village 33",
                censusCode: "520719",
                dateOfOccurance: "22-Dec-22",
                timeOfOccurance: "00:47:45",
                faultResolutionDate: "22-Dec-22",
                faultResolutionTime: "01:20:16",
                tisSecs: "1951",
                tisMins: "32.52",
                category: "Backhaul"
            },
            {
                outageID: "840740",
                project: "LWE II",
                state: "Chhattisgarh",
                siteID: "I-MP-BNPR-Tower-6062",
                villageName: "Village 37",
                censusCode: "448059",
                dateOfOccurance: "22-Dec-22",
                timeOfOccurance: "00:00:00",
                faultResolutionDate: "22-Dec-22",
                faultResolutionTime: "23:59:00",
                tisSecs: "86399",
                tisMins: "1439.98",
                category: "Power"
            },
            {
                outageID: "840797",
                project: "LWE II",
                state: "Chhattisgarh",
                siteID: "I-MP-PAJR-Tower-6148",
                villageName: "Village 38",
                censusCode: "448315",
                dateOfOccurance: "22-Dec-22",
                timeOfOccurance: "00:00:00",
                faultResolutionDate: "22-Dec-22",
                faultResolutionTime: "23:59:00",
                tisSecs: "86399",
                tisMins: "1439.98",
                category: "Power"
            },
            {
                outageID: "840719",
                project: "LWE II",
                state: "Chhattisgarh",
                siteID: "I-MP-BHRH-Tower-6068",
                villageName: "Village 12",
                censusCode: "451348",
                dateOfOccurance: "21-Dec-22",
                timeOfOccurance: "23:13:00",
                faultResolutionDate: "21-Dec-22",
                faultResolutionTime: "23:35:00",
                tisSecs: "1350",
                tisMins: "22.5",
                category: "Backhaul"
            },
            {
                outageID: "840783",
                project: "LWE II",
                state: "Chhattisgarh",
                siteID: "I-MP-NGRI-Tower-6104",
                villageName: "Village 39",
                censusCode: "447263",
                dateOfOccurance: "21-Dec-22",
                timeOfOccurance: "18:14:00",
                faultResolutionDate: "21-Dec-22",
                faultResolutionTime: "19:39:00",
                tisSecs: "5104",
                tisMins: "85.07",
                category: "Backhaul"
            },
            {
                outageID: "836183",
                project: "project 354",
                state: "Rajasthan",
                siteID: "I-RJ-JLMR-Tower-6166",
                villageName: "Village 40",
                censusCode: "85851",
                dateOfOccurance: "21-Dec-22",
                timeOfOccurance: "17:04:01",
                faultResolutionDate: "21-Dec-22",
                faultResolutionTime: "17:26:17",
                tisSecs: "1336",
                tisMins: "22.27",
                category: "Backhaul"
            },
            {
                outageID: "836108",
                project: "project 354",
                state: "Jammu",
                siteID: "I-JK-ATOL-Tower-6026",
                villageName: "Village 11",
                censusCode: "4734",
                dateOfOccurance: "21-Dec-22",
                timeOfOccurance: "16:01:12",
                faultResolutionDate: "21-Dec-22",
                faultResolutionTime: "16:18:42",
                tisSecs: "1050",
                tisMins: "17.5",
                category: "Backhaul"
            },
            {
                outageID: "836139",
                project: "502_MP",
                state: "Madhya Pradesh",
                siteID: "I-MP-CHGI-Tower-6112",
                villageName: "Village 14",
                censusCode: "503627",
                dateOfOccurance: "21-Dec-22",
                timeOfOccurance: "15:41:42",
                faultResolutionDate: "21-Dec-22",
                faultResolutionTime: "17:16:42",
                tisSecs: "5700",
                tisMins: "95",
                category: "Backhaul"
            },
            {
                outageID: "836140",
                project: "502_MP",
                state: "Madhya Pradesh",
                siteID: "I-MP-CHGI-Tower-6111",
                villageName: "Village 15",
                censusCode: "503626",
                dateOfOccurance: "21-Dec-22",
                timeOfOccurance: "15:41:42",
                faultResolutionDate: "21-Dec-22",
                faultResolutionTime: "17:16:42",
                tisSecs: "5700",
                tisMins: "95",
                category: "Backhaul"
            },
            {
                outageID: "836101",
                project: "project 354",
                state: "Jammu",
                siteID: "I-JK-ATOL-Tower-6026",
                villageName: "Village 11",
                censusCode: "4734",
                dateOfOccurance: "21-Dec-22",
                timeOfOccurance: "15:30:42",
                faultResolutionDate: "21-Dec-22",
                faultResolutionTime: "15:56:42",
                tisSecs: "1560",
                tisMins: "26",
                category: "Backhaul"
            },
            {
                outageID: "836117",
                project: "project 354",
                state: "Jammu",
                siteID: "I-JK-GNDH-Tower-6041",
                villageName: "Village 41",
                censusCode: "4727",
                dateOfOccurance: "21-Dec-22",
                timeOfOccurance: "15:30:12",
                faultResolutionDate: "21-Dec-22",
                faultResolutionTime: "15:55:16",
                tisSecs: "1504",
                tisMins: "25.07",
                category: "Backhaul"
            },
            {
                outageID: "836154",
                project: "project 354",
                state: "Gujarat",
                siteID: "I-GJ-DDPA-Tower-6058",
                villageName: "Village 42",
                censusCode: "521568",
                dateOfOccurance: "21-Dec-22",
                timeOfOccurance: "15:27:46",
                faultResolutionDate: "21-Dec-22",
                faultResolutionTime: "15:43:17",
                tisSecs: "931",
                tisMins: "15.52",
                category: "Backhaul"
            },
            {
                outageID: "836159",
                project: "project 354",
                state: "Gujarat",
                siteID: "I-GJ-DDPA-Tower-6070",
                villageName: "Village 43",
                censusCode: "521565|521564",
                dateOfOccurance: "21-Dec-22",
                timeOfOccurance: "15:27:46",
                faultResolutionDate: "21-Dec-22",
                faultResolutionTime: "15:43:17",
                tisSecs: "931",
                tisMins: "15.52",
                category: "Backhaul"
            },
            {
                outageID: "836158",
                project: "project 354",
                state: "Gujarat",
                siteID: "I-GJ-DDPA-Tower-6067",
                villageName: "Village 44",
                censusCode: "521566",
                dateOfOccurance: "21-Dec-22",
                timeOfOccurance: "15:27:46",
                faultResolutionDate: "21-Dec-22",
                faultResolutionTime: "15:43:17",
                tisSecs: "931",
                tisMins: "15.52",
                category: "Backhaul"
            },
            {
                outageID: "836157",
                project: "project 354",
                state: "Gujarat",
                siteID: "I-GJ-GDHW-Tower-6020",
                villageName: "Village 45",
                censusCode: "521547",
                dateOfOccurance: "21-Dec-22",
                timeOfOccurance: "15:27:46",
                faultResolutionDate: "21-Dec-22",
                faultResolutionTime: "15:43:17",
                tisSecs: "931",
                tisMins: "15.52",
                category: "Backhaul"
            },
            {
                outageID: "836156",
                project: "project 354",
                state: "Gujarat",
                siteID: "I-GJ-DDPA-Tower-6068",
                villageName: "Village 46",
                censusCode: "521590",
                dateOfOccurance: "21-Dec-22",
                timeOfOccurance: "15:27:46",
                faultResolutionDate: "21-Dec-22",
                faultResolutionTime: "15:43:17",
                tisSecs: "931",
                tisMins: "15.52",
                category: "Backhaul"
            },
            {
                outageID: "836155",
                project: "project 354",
                state: "Gujarat",
                siteID: "I-GJ-DDPA-Tower-6071",
                villageName: "Village 47",
                censusCode: "521567",
                dateOfOccurance: "21-Dec-22",
                timeOfOccurance: "15:27:46",
                faultResolutionDate: "21-Dec-22",
                faultResolutionTime: "15:43:17",
                tisSecs: "931",
                tisMins: "15.52",
                category: "Backhaul"
            },
            {
                outageID: "840716",
                project: "LWE II",
                state: "Chhattisgarh",
                siteID: "I-MP-BHRH-Tower-6068",
                villageName: "Village 12",
                censusCode: "451348",
                dateOfOccurance: "21-Dec-22",
                timeOfOccurance: "15:27:00",
                faultResolutionDate: "21-Dec-22",
                faultResolutionTime: "15:46:00",
                tisSecs: "1141",
                tisMins: "19.02",
                category: "Backhaul"
            },
            {
                outageID: "840741",
                project: "LWE II",
                state: "Chhattisgarh",
                siteID: "I-MP-KONT-Tower-6126",
                villageName: "Village 48",
                censusCode: "450460",
                dateOfOccurance: "21-Dec-22",
                timeOfOccurance: "14:31:00",
                faultResolutionDate: "21-Dec-22",
                faultResolutionTime: "17:55:00",
                tisSecs: "12279",
                tisMins: "204.65",
                category: "Backhaul"
            },
            {
                outageID: "840748",
                project: "LWE II",
                state: "Chhattisgarh",
                siteID: "I-MP-KONT-Tower-6144",
                villageName: "Village 49",
                censusCode: "450352",
                dateOfOccurance: "21-Dec-22",
                timeOfOccurance: "14:31:00",
                faultResolutionDate: "21-Dec-22",
                faultResolutionTime: "17:55:00",
                tisSecs: "12279",
                tisMins: "204.65",
                category: "Backhaul"
            },
            {
                outageID: "836141",
                project: "502_MP",
                state: "Madhya Pradesh",
                siteID: "I-MP-PANS-Tower-6016",
                villageName: "Village 13",
                censusCode: "478464",
                dateOfOccurance: "21-Dec-22",
                timeOfOccurance: "13:56:56",
                faultResolutionDate: "21-Dec-22",
                faultResolutionTime: "14:57:31",
                tisSecs: "3635",
                tisMins: "60.58",
                category: "Backhaul"
            },
            {
                outageID: "835615",
                project: "project 354",
                state: "Uttar Pradesh (East)",
                siteID: "I-UE-BAAB-Tower-6102",
                villageName: "Village 50",
                censusCode: "172801",
                dateOfOccurance: "21-Dec-22",
                timeOfOccurance: "13:32:43",
                faultResolutionDate: "21-Dec-22",
                faultResolutionTime: "14:25:43",
                tisSecs: "3180",
                tisMins: "53",
                category: "Backhaul"
            },
            {
                outageID: "836100",
                project: "project 354",
                state: "Jammu",
                siteID: "I-JK-ATOL-Tower-6026",
                villageName: "Village 11",
                censusCode: "4734",
                dateOfOccurance: "21-Dec-22",
                timeOfOccurance: "13:29:12",
                faultResolutionDate: "21-Dec-22",
                faultResolutionTime: "13:55:12",
                tisSecs: "1560",
                tisMins: "26",
                category: "Backhaul"
            },
            {
                outageID: "836098",
                project: "project 354",
                state: "Kashmir",
                siteID: "I-JK-BONY-Tower-6044",
                villageName: "Village 2",
                censusCode: "2596",
                dateOfOccurance: "21-Dec-22",
                timeOfOccurance: "13:07:43",
                faultResolutionDate: "21-Dec-22",
                faultResolutionTime: "16:17:20",
                tisSecs: "11377",
                tisMins: "189.62",
                category: "Backhaul"
            },
            {
                outageID: "836099",
                project: "project 354",
                state: "Jammu",
                siteID: "I-JK-ATOL-Tower-6026",
                villageName: "Village 11",
                censusCode: "4734",
                dateOfOccurance: "21-Dec-22",
                timeOfOccurance: "13:01:12",
                faultResolutionDate: "21-Dec-22",
                faultResolutionTime: "13:18:42",
                tisSecs: "1050",
                tisMins: "17.5",
                category: "Backhaul"
            },
            {
                outageID: "840715",
                project: "LWE II",
                state: "Chhattisgarh",
                siteID: "I-MP-BHRH-Tower-6068",
                villageName: "Village 12",
                censusCode: "451348",
                dateOfOccurance: "21-Dec-22",
                timeOfOccurance: "12:47:00",
                faultResolutionDate: "21-Dec-22",
                faultResolutionTime: "13:08:00",
                tisSecs: "1261",
                tisMins: "21.02",
                category: "Backhaul"
            },
            {
                outageID: "836177",
                project: "Assam",
                state: "Assam",
                siteID: "I-AS-HFLG-Tower-6074",
                villageName: "Village 17",
                censusCode: "298406",
                dateOfOccurance: "21-Dec-22",
                timeOfOccurance: "12:00:12",
                faultResolutionDate: "21-Dec-22",
                faultResolutionTime: "14:03:26",
                tisSecs: "7380",
                tisMins: "123",
                category: "Power"
            },
            {
                outageID: "836184",
                project: "project 354",
                state: "Rajasthan",
                siteID: "I-RJ-PONP-Tower-6180",
                villageName: "Village 51",
                censusCode: "86200",
                dateOfOccurance: "21-Dec-22",
                timeOfOccurance: "11:58:05",
                faultResolutionDate: "21-Dec-22",
                faultResolutionTime: "16:07:04",
                tisSecs: "14939",
                tisMins: "248.98",
                category: "Backhaul"
            },
            {
                outageID: "835614",
                project: "project 354",
                state: "Uttar Pradesh (East)",
                siteID: "I-UE-BAAB-Tower-6102",
                villageName: "Village 50",
                censusCode: "172801",
                dateOfOccurance: "21-Dec-22",
                timeOfOccurance: "11:54:43",
                faultResolutionDate: "21-Dec-22",
                faultResolutionTime: "12:06:13",
                tisSecs: "690",
                tisMins: "11.5",
                category: "Backhaul"
            },
            {
                outageID: "836071",
                project: "project 354",
                state: "Kashmir",
                siteID: "I-JK-BONY-Tower-6044",
                villageName: "Village 2",
                censusCode: "2596",
                dateOfOccurance: "21-Dec-22",
                timeOfOccurance: "11:21:40",
                faultResolutionDate: "21-Dec-22",
                faultResolutionTime: "11:29:06",
                tisSecs: "446",
                tisMins: "7.43",
                category: "Backhaul"
            },
            {
                outageID: "836075",
                project: "project 354",
                state: "Kashmir",
                siteID: "I-JK-BONY-Tower-6044",
                villageName: "Village 2",
                censusCode: "2596",
                dateOfOccurance: "21-Dec-22",
                timeOfOccurance: "11:10:40",
                faultResolutionDate: "21-Dec-22",
                faultResolutionTime: "11:19:08",
                tisSecs: "508",
                tisMins: "8.47",
                category: "Backhaul"
            },
            {
                outageID: "836174",
                project: "Assam",
                state: "Assam",
                siteID: "I-AS-HMRN-Tower-6146",
                villageName: "Village 52",
                censusCode: "295355|295361",
                dateOfOccurance: "21-Dec-22",
                timeOfOccurance: "11:00:42",
                faultResolutionDate: "21-Dec-22",
                faultResolutionTime: "11:18:42",
                tisSecs: "1080",
                tisMins: "18",
                category: "Backhaul"
            },
            {
                outageID: "836179",
                project: "Assam",
                state: "Assam",
                siteID: "I-AS-HMRN-Tower-6276",
                villageName: "Village 53",
                censusCode: "295773 | 295774 | 295845",
                dateOfOccurance: "21-Dec-22",
                timeOfOccurance: "11:00:42",
                faultResolutionDate: "21-Dec-22",
                faultResolutionTime: "11:18:42",
                tisSecs: "1080",
                tisMins: "18",
                category: "Backhaul"
            },
            {
                outageID: "836178",
                project: "Assam",
                state: "Assam",
                siteID: "I-AS-HMRN-Tower-6282",
                villageName: "Village 54",
                censusCode: "295306 | 295302",
                dateOfOccurance: "21-Dec-22",
                timeOfOccurance: "11:00:42",
                faultResolutionDate: "21-Dec-22",
                faultResolutionTime: "11:18:42",
                tisSecs: "1080",
                tisMins: "18",
                category: "Backhaul"
            },
            {
                outageID: "836176",
                project: "Assam",
                state: "Assam",
                siteID: "I-AS-HMRN-Tower-6216",
                villageName: "Village 55",
                censusCode: "295834",
                dateOfOccurance: "21-Dec-22",
                timeOfOccurance: "11:00:42",
                faultResolutionDate: "21-Dec-22",
                faultResolutionTime: "11:18:42",
                tisSecs: "1080",
                tisMins: "18",
                category: "Backhaul"
            },
            {
                outageID: "836175",
                project: "Assam",
                state: "Assam",
                siteID: "I-AS-HMRN-Tower-6271",
                villageName: "Village 56",
                censusCode: "295830",
                dateOfOccurance: "21-Dec-22",
                timeOfOccurance: "11:00:42",
                faultResolutionDate: "21-Dec-22",
                faultResolutionTime: "11:18:42",
                tisSecs: "1080",
                tisMins: "18",
                category: "Backhaul"
            },
            {
                outageID: "836109",
                project: "project 354",
                state: "Jammu",
                siteID: "I-JK-ATOL-Tower-6027",
                villageName: "Village 57",
                censusCode: "4789",
                dateOfOccurance: "21-Dec-22",
                timeOfOccurance: "10:40:42",
                faultResolutionDate: "21-Dec-22",
                faultResolutionTime: "18:10:12",
                tisSecs: "26970",
                tisMins: "449.5",
                category: "Backhaul"
            },
            {
                outageID: "836076",
                project: "project 354",
                state: "Kashmir",
                siteID: "I-JK-SANK-Tower-6012",
                villageName: "Village 58",
                censusCode: "1044",
                dateOfOccurance: "21-Dec-22",
                timeOfOccurance: "09:15:02",
                faultResolutionDate: "21-Dec-22",
                faultResolutionTime: "09:23:30",
                tisSecs: "508",
                tisMins: "8.47",
                category: "Power"
            },
            {
                outageID: "840713",
                project: "LWE II",
                state: "Chhattisgarh",
                siteID: "I-MP-BHRH-Tower-6068",
                villageName: "Village 12",
                censusCode: "451348",
                dateOfOccurance: "21-Dec-22",
                timeOfOccurance: "08:27:00",
                faultResolutionDate: "21-Dec-22",
                faultResolutionTime: "09:00:00",
                tisSecs: "1982",
                tisMins: "33.03",
                category: "Backhaul"
            },
            {
                outageID: "840798",
                project: "LWE II",
                state: "Chhattisgarh",
                siteID: "I-MP-PATR-Tower-6078",
                villageName: "Village 59",
                censusCode: "462090",
                dateOfOccurance: "21-Dec-22",
                timeOfOccurance: "06:28:00",
                faultResolutionDate: "21-Dec-22",
                faultResolutionTime: "08:18:00",
                tisSecs: "6577",
                tisMins: "109.62",
                category: "Backhaul"
            },
            {
                outageID: "840736",
                project: "LWE II",
                state: "Chhattisgarh",
                siteID: "I-MP-BLRP-Tower-6066",
                villageName: "Village 60",
                censusCode: "431947",
                dateOfOccurance: "21-Dec-22",
                timeOfOccurance: "03:26:00",
                faultResolutionDate: "21-Dec-22",
                faultResolutionTime: "03:39:00",
                tisSecs: "780",
                tisMins: "13",
                category: "Equipment"
            },
            {
                outageID: "836093",
                project: "project 354",
                state: "Kashmir",
                siteID: "I-JK-LEEH-Tower-6051",
                villageName: "Village 61",
                censusCode: "889",
                dateOfOccurance: "21-Dec-22",
                timeOfOccurance: "03:14:23",
                faultResolutionDate: "21-Dec-22",
                faultResolutionTime: "10:43:01",
                tisSecs: "26918",
                tisMins: "448.63",
                category: "Power"
            },
            {
                outageID: "840735",
                project: "LWE II",
                state: "Chhattisgarh",
                siteID: "I-MP-BLRP-Tower-6066",
                villageName: "Village 60",
                censusCode: "431947",
                dateOfOccurance: "21-Dec-22",
                timeOfOccurance: "02:50:00",
                faultResolutionDate: "21-Dec-22",
                faultResolutionTime: "03:17:00",
                tisSecs: "1620",
                tisMins: "27",
                category: "Equipment"
            },
            {
                outageID: "840804",
                project: "LWE II",
                state: "Chhattisgarh",
                siteID: "I-MP-SRPL-Tower-6086",
                villageName: "Village 62",
                censusCode: "445954",
                dateOfOccurance: "21-Dec-22",
                timeOfOccurance: "02:22:00",
                faultResolutionDate: "21-Dec-22",
                faultResolutionTime: "02:41:00",
                tisSecs: "1110",
                tisMins: "18.5",
                category: "Equipment"
            },
            {
                outageID: "840803",
                project: "LWE II",
                state: "Chhattisgarh",
                siteID: "I-MP-SRPL-Tower-6086",
                villageName: "Village 62",
                censusCode: "445954",
                dateOfOccurance: "21-Dec-22",
                timeOfOccurance: "01:43:00",
                faultResolutionDate: "21-Dec-22",
                faultResolutionTime: "02:18:00",
                tisSecs: "2102",
                tisMins: "35.03",
                category: "Equipment"
            },
            {
                outageID: "836116",
                project: "project 354",
                state: "Jammu",
                siteID: "I-JK-MRWH-Tower-6026",
                villageName: "Village 63",
                censusCode: "4730",
                dateOfOccurance: "21-Dec-22",
                timeOfOccurance: "00:52:11",
                faultResolutionDate: "21-Dec-22",
                faultResolutionTime: "00:59:11",
                tisSecs: "420",
                tisMins: "7",
                category: "Backhaul"
            },
            {
                outageID: "840739",
                project: "LWE II",
                state: "Chhattisgarh",
                siteID: "I-MP-BNPR-Tower-6062",
                villageName: "Village 37",
                censusCode: "448059",
                dateOfOccurance: "21-Dec-22",
                timeOfOccurance: "00:00:00",
                faultResolutionDate: "21-Dec-22",
                faultResolutionTime: "23:59:00",
                tisSecs: "86399",
                tisMins: "1439.98",
                category: "Power"
            },
            {
                outageID: "840796",
                project: "LWE II",
                state: "Chhattisgarh",
                siteID: "I-MP-PAJR-Tower-6148",
                villageName: "Village 38",
                censusCode: "448315",
                dateOfOccurance: "21-Dec-22",
                timeOfOccurance: "00:00:00",
                faultResolutionDate: "21-Dec-22",
                faultResolutionTime: "23:59:00",
                tisSecs: "86399",
                tisMins: "1439.98",
                category: "Power"
            },
            {
                outageID: "836115",
                project: "project 354",
                state: "Jammu",
                siteID: "I-JK-MRWH-Tower-6026",
                villageName: "Village 63",
                censusCode: "4730",
                dateOfOccurance: "20-Dec-22",
                timeOfOccurance: "21:51:42",
                faultResolutionDate: "20-Dec-22",
                faultResolutionTime: "22:02:42",
                tisSecs: "660",
                tisMins: "11",
                category: "Backhaul"
            },
            {
                outageID: "840764",
                project: "LWE II",
                state: "Chhattisgarh",
                siteID: "I-MP-MNPU-Tower-6071",
                villageName: "Village 64",
                censusCode: "445427| 445428",
                dateOfOccurance: "20-Dec-22",
                timeOfOccurance: "20:38:00",
                faultResolutionDate: "20-Dec-22",
                faultResolutionTime: "11:59:00",
                tisSecs: "12070",
                tisMins: "201.17",
                category: "Backhaul"
            },
            {
                outageID: "840779",
                project: "LWE II",
                state: "Chhattisgarh",
                siteID: "I-MP-MNPU-Tower-6085",
                villageName: "Village 65",
                censusCode: "445526 | 445429",
                dateOfOccurance: "20-Dec-22",
                timeOfOccurance: "20:38:00",
                faultResolutionDate: "20-Dec-22",
                faultResolutionTime: "11:59:00",
                tisSecs: "12071",
                tisMins: "201.18",
                category: "Backhaul"
            },
            {
                outageID: "840778",
                project: "LWE II",
                state: "Chhattisgarh",
                siteID: "I-MP-MNPU-Tower-6080",
                villageName: "Village 66",
                censusCode: "445514",
                dateOfOccurance: "20-Dec-22",
                timeOfOccurance: "20:38:00",
                faultResolutionDate: "20-Dec-22",
                faultResolutionTime: "11:59:00",
                tisSecs: "12071",
                tisMins: "201.18",
                category: "Backhaul"
            },
            {
                outageID: "840768",
                project: "LWE II",
                state: "Chhattisgarh",
                siteID: "I-MP-MNPU-Tower-6075",
                villageName: "Village 67",
                censusCode: "445424",
                dateOfOccurance: "20-Dec-22",
                timeOfOccurance: "20:38:00",
                faultResolutionDate: "20-Dec-22",
                faultResolutionTime: "11:59:00",
                tisSecs: "12071",
                tisMins: "201.18",
                category: "Backhaul"
            },
            {
                outageID: "840766",
                project: "LWE II",
                state: "Chhattisgarh",
                siteID: "I-MP-MNPU-Tower-6074",
                villageName: "Village 68",
                censusCode: "445524",
                dateOfOccurance: "20-Dec-22",
                timeOfOccurance: "20:38:00",
                faultResolutionDate: "20-Dec-22",
                faultResolutionTime: "11:59:00",
                tisSecs: "12071",
                tisMins: "201.18",
                category: "Backhaul"
            },
            {
                outageID: "840710",
                project: "LWE II",
                state: "Chhattisgarh",
                siteID: "I-MP-BHRH-Tower-6068",
                villageName: "Village 12",
                censusCode: "451348",
                dateOfOccurance: "20-Dec-22",
                timeOfOccurance: "18:49:00",
                faultResolutionDate: "20-Dec-22",
                faultResolutionTime: "19:09:00",
                tisSecs: "1201",
                tisMins: "20.02",
                category: "Backhaul"
            },
            {
                outageID: "836114",
                project: "project 354",
                state: "Jammu",
                siteID: "I-JK-MRWH-Tower-6026",
                villageName: "Village 63",
                censusCode: "4730",
                dateOfOccurance: "20-Dec-22",
                timeOfOccurance: "17:16:42",
                faultResolutionDate: "20-Dec-22",
                faultResolutionTime: "17:27:12",
                tisSecs: "630",
                tisMins: "10.5",
                category: "Backhaul"
            },
            {
                outageID: "835616",
                project: "502_UP",
                state: "Uttar Pradesh (East)",
                siteID: "I-UE-RBGJ-Tower-6201",
                villageName: "Village 69",
                censusCode: "213970",
                dateOfOccurance: "20-Dec-22",
                timeOfOccurance: "16:51:42",
                faultResolutionDate: "20-Dec-22",
                faultResolutionTime: "17:07:53",
                tisSecs: "971",
                tisMins: "16.18",
                category: "Equipment"
            },
            {
                outageID: "836083",
                project: "project 354",
                state: "Kashmir",
                siteID: "I-JK-BONY-Tower-6044",
                villageName: "Village 2",
                censusCode: "2596",
                dateOfOccurance: "20-Dec-22",
                timeOfOccurance: "16:43:13",
                faultResolutionDate: "20-Dec-22",
                faultResolutionTime: "16:55:09",
                tisSecs: "716",
                tisMins: "11.93",
                category: "Backhaul"
            },
            {
                outageID: "836073",
                project: "project 354",
                state: "Kashmir",
                siteID: "I-JK-LEEH-Tower-6068",
                villageName: "Village 4",
                censusCode: "906",
                dateOfOccurance: "20-Dec-22",
                timeOfOccurance: "16:33:23",
                faultResolutionDate: "20-Dec-22",
                faultResolutionTime: "16:40:51",
                tisSecs: "448",
                tisMins: "7.47",
                category: "Backhaul"
            },
            {
                outageID: "836074",
                project: "project 354",
                state: "Kashmir",
                siteID: "I-JK-BONY-Tower-6044",
                villageName: "Village 2",
                censusCode: "2596",
                dateOfOccurance: "20-Dec-22",
                timeOfOccurance: "16:23:13",
                faultResolutionDate: "20-Dec-22",
                faultResolutionTime: "16:30:43",
                tisSecs: "450",
                tisMins: "7.5",
                category: "Backhaul"
            },
            {
                outageID: "836065",
                project: "project 354",
                state: "Kashmir",
                siteID: "I-JK-BONY-Tower-6044",
                villageName: "Village 2",
                censusCode: "2596",
                dateOfOccurance: "20-Dec-22",
                timeOfOccurance: "16:13:44",
                faultResolutionDate: "20-Dec-22",
                faultResolutionTime: "16:20:10",
                tisSecs: "386",
                tisMins: "6.43",
                category: "Backhaul"
            },
            {
                outageID: "836098",
                project: "project 354",
                state: "Jammu",
                siteID: "I-JK-ATOL-Tower-6026",
                villageName: "Village 11",
                censusCode: "4734",
                dateOfOccurance: "20-Dec-22",
                timeOfOccurance: "16:08:12",
                faultResolutionDate: "20-Dec-22",
                faultResolutionTime: "16:24:12",
                tisSecs: "960",
                tisMins: "16",
                category: "Backhaul"
            },
            {
                outageID: "836097",
                project: "project 354",
                state: "Jammu",
                siteID: "I-JK-ATOL-Tower-6026",
                villageName: "Village 11",
                censusCode: "4734",
                dateOfOccurance: "20-Dec-22",
                timeOfOccurance: "15:53:12",
                faultResolutionDate: "20-Dec-22",
                faultResolutionTime: "16:00:12",
                tisSecs: "420",
                tisMins: "7",
                category: "Backhaul"
            },
            {
                outageID: "836089",
                project: "project 354",
                state: "Kashmir",
                siteID: "I-JK-BONY-Tower-6044",
                villageName: "Village 2",
                censusCode: "2596",
                dateOfOccurance: "20-Dec-22",
                timeOfOccurance: "15:22:42",
                faultResolutionDate: "20-Dec-22",
                faultResolutionTime: "16:05:09",
                tisSecs: "2547",
                tisMins: "42.45",
                category: "Backhaul"
            },
            {
                outageID: "836096",
                project: "project 354",
                state: "Jammu",
                siteID: "I-JK-ATOL-Tower-6026",
                villageName: "Village 11",
                censusCode: "4734",
                dateOfOccurance: "20-Dec-22",
                timeOfOccurance: "14:56:12",
                faultResolutionDate: "20-Dec-22",
                faultResolutionTime: "15:17:42",
                tisSecs: "1290",
                tisMins: "21.5",
                category: "Backhaul"
            },
            {
                outageID: "836090",
                project: "project 354",
                state: "Kashmir",
                siteID: "I-JK-BONY-Tower-6044",
                villageName: "Village 2",
                censusCode: "2596",
                dateOfOccurance: "20-Dec-22",
                timeOfOccurance: "14:10:10",
                faultResolutionDate: "20-Dec-22",
                faultResolutionTime: "15:22:10",
                tisSecs: "4320",
                tisMins: "72",
                category: "Backhaul"
            },
            {
                outageID: "836095",
                project: "project 354",
                state: "Jammu",
                siteID: "I-JK-ATOL-Tower-6026",
                villageName: "Village 11",
                censusCode: "4734",
                dateOfOccurance: "20-Dec-22",
                timeOfOccurance: "13:32:42",
                faultResolutionDate: "20-Dec-22",
                faultResolutionTime: "14:17:42",
                tisSecs: "2700",
                tisMins: "45",
                category: "Backhaul"
            },
            {
                outageID: "836088",
                project: "project 354",
                state: "Kashmir",
                siteID: "I-JK-BONY-Tower-6044",
                villageName: "Village 2",
                censusCode: "2596",
                dateOfOccurance: "20-Dec-22",
                timeOfOccurance: "13:30:39",
                faultResolutionDate: "20-Dec-22",
                faultResolutionTime: "14:08:06",
                tisSecs: "2247",
                tisMins: "37.45",
                category: "Backhaul"
            },
            {
                outageID: "836180",
                project: "project 354",
                state: "Uttar Pradesh (West)",
                siteID: "I-UW-PRNP-Tower-6122",
                villageName: "Village 70",
                censusCode: "132356",
                dateOfOccurance: "20-Dec-22",
                timeOfOccurance: "13:23:12",
                faultResolutionDate: "20-Dec-22",
                faultResolutionTime: "13:31:42",
                tisSecs: "510",
                tisMins: "8.5",
                category: "Backhaul"
            },
            {
                outageID: "836081",
                project: "project 354",
                state: "Kashmir",
                siteID: "I-JK-SANK-Tower-6012",
                villageName: "Village 58",
                censusCode: "1044",
                dateOfOccurance: "20-Dec-22",
                timeOfOccurance: "13:04:16",
                faultResolutionDate: "20-Dec-22",
                faultResolutionTime: "13:15:15",
                tisSecs: "659",
                tisMins: "10.98",
                category: "Power"
            },
            {
                outageID: "836113",
                project: "project 354",
                state: "Jammu",
                siteID: "I-JK-MRWH-Tower-6026",
                villageName: "Village 63",
                censusCode: "4730",
                dateOfOccurance: "20-Dec-22",
                timeOfOccurance: "13:02:42",
                faultResolutionDate: "20-Dec-22",
                faultResolutionTime: "13:41:24",
                tisSecs: "2322",
                tisMins: "38.7",
                category: "Backhaul"
            },
            {
                outageID: "836094",
                project: "project 354",
                state: "Jammu",
                siteID: "I-JK-ATOL-Tower-6026",
                villageName: "Village 11",
                censusCode: "4734",
                dateOfOccurance: "20-Dec-22",
                timeOfOccurance: "12:47:42",
                faultResolutionDate: "20-Dec-22",
                faultResolutionTime: "13:26:42",
                tisSecs: "2340",
                tisMins: "39",
                category: "Backhaul"
            },
            {
                outageID: "836110",
                project: "project 354",
                state: "Jammu",
                siteID: "I-JK-GNDH-Tower-6026",
                villageName: "Village 71",
                censusCode: "4340",
                dateOfOccurance: "20-Dec-22",
                timeOfOccurance: "12:35:12",
                faultResolutionDate: "20-Dec-22",
                faultResolutionTime: "15:11:12",
                tisSecs: "9360",
                tisMins: "156",
                category: "Backhaul"
            },
            {
                outageID: "836118",
                project: "project 354",
                state: "Jammu",
                siteID: "I-JK-GNDH-Tower-6011",
                villageName: "Village 72",
                censusCode: "4388",
                dateOfOccurance: "20-Dec-22",
                timeOfOccurance: "12:35:12",
                faultResolutionDate: "20-Dec-22",
                faultResolutionTime: "15:11:12",
                tisSecs: "9360",
                tisMins: "156",
                category: "Power"
            },
            {
                outageID: "836111",
                project: "project 354",
                state: "Jammu",
                siteID: "I-JK-GNDH-Tower-6010",
                villageName: "Village 73",
                censusCode: "4386",
                dateOfOccurance: "20-Dec-22",
                timeOfOccurance: "12:35:12",
                faultResolutionDate: "20-Dec-22",
                faultResolutionTime: "15:11:12",
                tisSecs: "9360",
                tisMins: "156",
                category: "Backhaul"
            },
            {
                outageID: "840708",
                project: "LWE II",
                state: "Chhattisgarh",
                siteID: "I-MP-BHRH-Tower-6068",
                villageName: "Village 12",
                censusCode: "451348",
                dateOfOccurance: "20-Dec-22",
                timeOfOccurance: "12:15:00",
                faultResolutionDate: "20-Dec-22",
                faultResolutionTime: "12:56:00",
                tisSecs: "2432",
                tisMins: "40.53",
                category: "Backhaul"
            },
            {
                outageID: "836150",
                project: "LWE II",
                state: "Odisha",
                siteID: "I-OR-MARI-Tower-6060",
                villageName: "Village 74",
                censusCode: "430165",
                dateOfOccurance: "20-Dec-22",
                timeOfOccurance: "12:01:10",
                faultResolutionDate: "20-Dec-22",
                faultResolutionTime: "12:12:36",
                tisSecs: "686",
                tisMins: "11.43",
                category: "Backhaul"
            },
            {
                outageID: "840805",
                project: "LWE II",
                state: "Chhattisgarh",
                siteID: "I-MP-USUR-Tower-6061",
                villageName: "Village 75",
                censusCode: "450931",
                dateOfOccurance: "20-Dec-22",
                timeOfOccurance: "11:20:00",
                faultResolutionDate: "20-Dec-22",
                faultResolutionTime: "12:48:00",
                tisSecs: "5287",
                tisMins: "88.12",
                category: "Backhaul"
            },
            {
                outageID: "836078",
                project: "project 354",
                state: "Kashmir",
                siteID: "I-JK-BONY-Tower-6044",
                villageName: "Village 2",
                censusCode: "2596",
                dateOfOccurance: "20-Dec-22",
                timeOfOccurance: "11:19:04",
                faultResolutionDate: "20-Dec-22",
                faultResolutionTime: "11:26:31",
                tisSecs: "447",
                tisMins: "7.45",
                category: "Backhaul"
            },
            {
                outageID: "836070",
                project: "project 354",
                state: "Kashmir",
                siteID: "I-JK-BONY-Tower-6044",
                villageName: "Village 2",
                censusCode: "2596",
                dateOfOccurance: "20-Dec-22",
                timeOfOccurance: "11:09:34",
                faultResolutionDate: "20-Dec-22",
                faultResolutionTime: "11:16:59",
                tisSecs: "445",
                tisMins: "7.42",
                category: "Backhaul"
            },
            {
                outageID: "836173",
                project: "Assam",
                state: "Assam",
                siteID: "I-AS-HMRN-Tower-6200",
                villageName: "Village 76",
                censusCode: "295362|295439",
                dateOfOccurance: "20-Dec-22",
                timeOfOccurance: "10:39:42",
                faultResolutionDate: "20-Dec-22",
                faultResolutionTime: "18:34:27",
                tisSecs: "28500",
                tisMins: "475",
                category: "Power"
            },
            {
                outageID: "836178",
                project: "Assam",
                state: "Assam",
                siteID: "I-AS-HMRN-Tower-6245",
                villageName: "Village 77",
                censusCode: "295805",
                dateOfOccurance: "20-Dec-22",
                timeOfOccurance: "10:34:12",
                faultResolutionDate: "20-Dec-22",
                faultResolutionTime: "11:57:01",
                tisSecs: "4980",
                tisMins: "83",
                category: "Power"
            },
            {
                outageID: "836063",
                project: "project 354",
                state: "Kashmir",
                siteID: "I-JK-GURZ-Tower-6021",
                villageName: "Village 78",
                censusCode: "2726",
                dateOfOccurance: "20-Dec-22",
                timeOfOccurance: "10:16:03",
                faultResolutionDate: "20-Dec-22",
                faultResolutionTime: "10:22:14",
                tisSecs: "371",
                tisMins: "6.18",
                category: "Power"
            },
            {
                outageID: "836066",
                project: "project 354",
                state: "Kashmir",
                siteID: "I-JK-LEEH-Tower-6100",
                villageName: "Village 79",
                censusCode: "885",
                dateOfOccurance: "20-Dec-22",
                timeOfOccurance: "09:25:39",
                faultResolutionDate: "20-Dec-22",
                faultResolutionTime: "09:32:06",
                tisSecs: "387",
                tisMins: "6.45",
                category: "Backhaul"
            },
            {
                outageID: "836108",
                project: "project 354",
                state: "Jammu",
                siteID: "I-JK-ATOL-Tower-6027",
                villageName: "Village 57",
                censusCode: "4789",
                dateOfOccurance: "20-Dec-22",
                timeOfOccurance: "08:35:11",
                faultResolutionDate: "20-Dec-22",
                faultResolutionTime: "10:43:40",
                tisSecs: "7709",
                tisMins: "128.48",
                category: "Backhaul"
            },
            {
                outageID: "836149",
                project: "LWE II",
                state: "Odisha",
                siteID: "I-OR-MARI-Tower-6060",
                villageName: "Village 74",
                censusCode: "430165",
                dateOfOccurance: "20-Dec-22",
                timeOfOccurance: "08:34:48",
                faultResolutionDate: "20-Dec-22",
                faultResolutionTime: "12:04:23",
                tisSecs: "12575",
                tisMins: "209.58",
                category: "Backhaul"
            },
            {
                outageID: "836171",
                project: "Assam",
                state: "Assam",
                siteID: "I-AS-HMRN-Tower-6245",
                villageName: "Village 77",
                censusCode: "295805",
                dateOfOccurance: "20-Dec-22",
                timeOfOccurance: "07:16:12",
                faultResolutionDate: "20-Dec-22",
                faultResolutionTime: "09:32:49",
                tisSecs: "8220",
                tisMins: "137",
                category: "Power"
            },
            {
                outageID: "836086",
                project: "project 354",
                state: "Kashmir",
                siteID: "I-JK-BONY-Tower-6044",
                villageName: "Village 2",
                censusCode: "2596",
                dateOfOccurance: "20-Dec-22",
                timeOfOccurance: "05:42:54",
                faultResolutionDate: "20-Dec-22",
                faultResolutionTime: "06:12:20",
                tisSecs: "1766",
                tisMins: "29.43",
                category: "Backhaul"
            },
            {
                outageID: "836119",
                project: "project 354",
                state: "Uttar Pradesh (West)",
                siteID: "I-UW-PRNP-Tower-6122",
                villageName: "Village 70",
                censusCode: "132356",
                dateOfOccurance: "20-Dec-22",
                timeOfOccurance: "03:32:41",
                faultResolutionDate: "20-Dec-22",
                faultResolutionTime: "03:51:11",
                tisSecs: "1110",
                tisMins: "18.5",
                category: "Backhaul"
            },
            {
                outageID: "836118",
                project: "project 354",
                state: "Uttar Pradesh (West)",
                siteID: "I-UW-PRNP-Tower-6122",
                villageName: "Village 70",
                censusCode: "132356",
                dateOfOccurance: "20-Dec-22",
                timeOfOccurance: "02:57:41",
                faultResolutionDate: "20-Dec-22",
                faultResolutionTime: "03:29:41",
                tisSecs: "1920",
                tisMins: "32",
                category: "Backhaul"
            },
            {
                outageID: "836079",
                project: "project 354",
                state: "Kashmir",
                siteID: "I-JK-BONY-Tower-6044",
                villageName: "Village 2",
                censusCode: "2596",
                dateOfOccurance: "20-Dec-22",
                timeOfOccurance: "01:58:24",
                faultResolutionDate: "20-Dec-22",
                faultResolutionTime: "02:08:20",
                tisSecs: "596",
                tisMins: "9.93",
                category: "Backhaul"
            },
            {
                outageID: "836153",
                project: "project 354",
                state: "Gujarat",
                siteID: "I-GJ-GDHW-Tower-6014",
                villageName: "Village 80",
                censusCode: "521462",
                dateOfOccurance: "20-Dec-22",
                timeOfOccurance: "01:50:17",
                faultResolutionDate: "20-Dec-22",
                faultResolutionTime: "05:27:24",
                tisSecs: "13027",
                tisMins: "217.12",
                category: "Backhaul"
            },
            {
                outageID: "836067",
                project: "project 354",
                state: "Kashmir",
                siteID: "I-JK-BONY-Tower-6044",
                villageName: "Village 2",
                censusCode: "2596",
                dateOfOccurance: "20-Dec-22",
                timeOfOccurance: "01:18:52",
                faultResolutionDate: "20-Dec-22",
                faultResolutionTime: "01:25:48",
                tisSecs: "416",
                tisMins: "6.93",
                category: "Backhaul"
            },
            {
                outageID: "840705",
                project: "LWE II",
                state: "Chhattisgarh",
                siteID: "I-MP-BHRH-Tower-6068",
                villageName: "Village 12",
                censusCode: "451348",
                dateOfOccurance: "20-Dec-22",
                timeOfOccurance: "01:08:00",
                faultResolutionDate: "20-Dec-22",
                faultResolutionTime: "01:47:00",
                tisSecs: "2345",
                tisMins: "39.08",
                category: "Backhaul"
            },
            {
                outageID: "836080",
                project: "project 354",
                state: "Kashmir",
                siteID: "I-JK-BONY-Tower-6044",
                villageName: "Village 2",
                censusCode: "2596",
                dateOfOccurance: "20-Dec-22",
                timeOfOccurance: "01:02:22",
                faultResolutionDate: "20-Dec-22",
                faultResolutionTime: "01:12:18",
                tisSecs: "596",
                tisMins: "9.93",
                category: "Backhaul"
            },
            {
                outageID: "836077",
                project: "project 354",
                state: "Kashmir",
                siteID: "I-JK-BONY-Tower-6044",
                villageName: "Village 2",
                censusCode: "2596",
                dateOfOccurance: "20-Dec-22",
                timeOfOccurance: "00:40:20",
                faultResolutionDate: "20-Dec-22",
                faultResolutionTime: "00:49:17",
                tisSecs: "537",
                tisMins: "8.95",
                category: "Backhaul"
            },
            {
                outageID: "836107",
                project: "project 354",
                state: "Jammu",
                siteID: "I-JK-ATOL-Tower-6027",
                villageName: "Village 57",
                censusCode: "4789",
                dateOfOccurance: "20-Dec-22",
                timeOfOccurance: "00:34:11",
                faultResolutionDate: "20-Dec-22",
                faultResolutionTime: "08:29:54",
                tisSecs: "28543",
                tisMins: "475.72",
                category: "Backhaul"
            },
            {
                outageID: "836085",
                project: "project 354",
                state: "Kashmir",
                siteID: "I-JK-BONY-Tower-6044",
                villageName: "Village 2",
                censusCode: "2596",
                dateOfOccurance: "20-Dec-22",
                timeOfOccurance: "00:11:19",
                faultResolutionDate: "20-Dec-22",
                faultResolutionTime: "00:39:50",
                tisSecs: "1711",
                tisMins: "28.52",
                category: "Backhaul"
            },
            {
                outageID: "836069",
                project: "project 354",
                state: "Kashmir",
                siteID: "I-JK-BONY-Tower-6044",
                villageName: "Village 2",
                censusCode: "2596",
                dateOfOccurance: "20-Dec-22",
                timeOfOccurance: "00:03:47",
                faultResolutionDate: "20-Dec-22",
                faultResolutionTime: "00:10:49",
                tisSecs: "422",
                tisMins: "7.03",
                category: "Backhaul"
            },
            {
                outageID: "840738",
                project: "LWE II",
                state: "Chhattisgarh",
                siteID: "I-MP-BNPR-Tower-6062",
                villageName: "Village 37",
                censusCode: "448059",
                dateOfOccurance: "20-Dec-22",
                timeOfOccurance: "00:00:00",
                faultResolutionDate: "20-Dec-22",
                faultResolutionTime: "23:59:00",
                tisSecs: "86399",
                tisMins: "1439.98",
                category: "Power"
            },
            {
                outageID: "840795",
                project: "LWE II",
                state: "Chhattisgarh",
                siteID: "I-MP-PAJR-Tower-6148",
                villageName: "Village 38",
                censusCode: "448315",
                dateOfOccurance: "20-Dec-22",
                timeOfOccurance: "00:00:00",
                faultResolutionDate: "20-Dec-22",
                faultResolutionTime: "23:59:00",
                tisSecs: "86399",
                tisMins: "1439.98",
                category: "Power"
            }
        ],
        
    };





   